### ISSUE TITLE
Hackage release compatible with transformers 0.6

### ISSUE THREAD

**Issue by ali-abrar** [mainland/exception-transformers#9]
I see that https://github.com/mainland/exception-transformers/commit/0c6e2e97b82e4168fb96d96b4f4f1ba336754a1c made this library compatible with transformers-0.6. Would it be possible to get that change up on hackage? Thank you!

**Comment by mainland** [comment]
Only the tests are incompatible with transformers-0.6. Can't you install the package without the tests?

**Comment by mainland** [comment]
Fixed by 0c6e2e9.
